### ISSUE TITLE
iTerm2 Theme

### ISSUE THREAD

**Issue by shahmilav** [JhonnyRice/summer#1]
Hey!

GitHub Pull Requests did not work for me, but I created an iTerm2 theme. Know how I could contribute?

**Comment by shahmilav** [comment]
[summer.txt](https://github.com/JhonnyRice/summer/files/7938362/summer.txt)

Here is the file in case you wish to see it.

**Comment by rice7th** [comment]
Ok!

**Comment by rice7th** [comment]
Added!
