### ISSUE TITLE
Issue in iTerm2 file name

### ISSUE THREAD

**Issue by shahmilav** [JhonnyRice/summer#3]
Hey, I am the author of the iTerm2 theme.

In the repo, the name of the file is ```config.plist``` yet iTerm only supports .itermcolors files even though they are the same file. It would be great if you could change the file name to either config.itermcolors or summer.itermcolors (the latter preferred, as then the name "Summer" will show up in the iTerm theme switcher).

Sorry for not being clearer earlier.

**Comment by rice7th** [comment]
ok!
